### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by ljwharbers** [raphael-group/chisel#17]
Hi,

I was trying to prepare my bamfiles to match the input required for chisel using chisel_prep.py and I see you're actively working on this (many thanks!). I have a directory of bamfiles in the format of `{barcode}.dedup_q30.bam` and when I run the following command `chisel_prep.py -r /mnt/AchTeraD/Documents/references/hg19/hg19.fa -o /mnt/AchTeraD/data/BICRO249/NZ173/chisel-merged_bamfiles.bam --barcodelength 11 -j 24 bamfiles/*.bam`

I receive the following:
```
[2020-Dec-01 15:37:46]Setting up
[2020-Dec-01 15:37:46]Running in multiple BAM files mode
Traceback (most recent call last):
  File "miniconda3/envs/chisel/lib/python2.7/site-packages/chisel-0.0.4-py2.7.egg/src/chisel_prep.py", line 533, in <module>
    main()
  File "miniconda3/envs/chisel/lib/python2.7/site-packages/chisel-0.0.4-py2.7.egg/src/chisel_prep.py", line 137, in main
    barcoded, cells = run_B(args, tmpdir, errdir) if len(args['inputs']) == 1 else run_b(args, tmpdir, errdir, binfo=info)
  File "miniconda3/envs/chisel/lib/python2.7/site-packages/chisel-0.0.4-py2.7.egg/src/chisel_prep.py", line 278, in run_b
    par['barcodes'] = mkbarcodes(par['files'], args['barlength'], binfo=binfo)
  File "miniconda3/envs/chisel/lib/python2.7/site-packages/chisel-0.0.4-py2.7.egg/src/chisel_prep.py", line 325, in mkbarcodes
    map(lambda f : lanes[binfo[f]].append(f), files)
  File "miniconda3/envs/chisel/lib/python2.7/site-packages/chisel-0.0.4-py2.7.egg/src/chisel_prep.py", line 325, in <lambda>
    map(lambda f : lanes[binfo[f]].append(f), files)
TypeError: unhashable type: 'dict'
```

I wonder if you could help me with this.
Many thanks,
Luuk

**Comment by simozacca** [comment]
Thank you for the interest in the new command of CHISEL! `chisel_prep` will allow the user to easily and efficiently create a barcoded BAM file starting from all the standard formats for single-cell sequencing data. However, the command is still in the final phase of its development. Please allow us few more days to complete testing before proceeding with its usage.

We will update this issue once the command will be ready for release; thank you for the understanding.

**Comment by simozacca** [comment]
Thank you for your patience!

The new CHISEL command `chisel_prep` is ready in its first release on this repository! Please review the command documentation and please let us know of any issue you might have. We expect the new command to be soon included in the next bioconda release of CHISEL very soon.
