### ISSUE TITLE
Error while plotting!

### ISSUE THREAD

**Issue by jmfa** [raphael-group/chisel#30]
Hi,

Thanks for the nice tool.
I'm trying to run chisel on a scDNA-seq dataset composed of 26 cells.
I've successfully ran all steps of the pipeline but I get an error at the end while plotting:

`[2023-Oct-14 14:42:07]Plotting RDR and mirrored BAF plots for 20 random cells in rbplot_mirrored.png
Traceback (most recent call last):
  File "/mnt/netapp2/Store_uni/home/uvi/be/jfa/conda/envs/chisel/lib/python2.7/site-packages/chisel/Plotter.py", line 561, in <module>
    main()
  File "/mnt/netapp2/Store_uni/home/uvi/be/jfa/conda/envs/chisel/lib/python2.7/site-packages/chisel/Plotter.py", line 119, in main
    rbplot_mirrored(bins, chosen, args)
  File "/mnt/netapp2/Store_uni/home/uvi/be/jfa/conda/envs/chisel/lib/python2.7/site-packages/chisel/Plotter.py", line 296, in rbplot_mirrored
    g = sns.lmplot(**par)
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/regression.py", line 619, in lmplot
    facets.map_dataframe(regplot, x, y, **regplot_kws)
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 834, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 852, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/regression.py", line 812, in regplot
    x_jitter, y_jitter, color, label)
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/regression.py", line 116, in __init__
    self.dropna("x", "y", "units", "x_partial", "y_partial")
  File "/home/uvi/be/jfa/.local/lib/python2.7/site-packages/seaborn/regression.py", line 68, in dropna
    setattr(self, var, val[not_na])
IndexError: invalid index to scalar variable.
`

Any idea of what might be causing this issue?
Thanks in advance,
J

**Comment by simozacca** [comment]
You might have not enough cells to generate plots that are done only for a sample of cells; please try to running the plotting with the flag `--sample 1` to force to generate these plots only for a single cell. Also, make sure to re-run the `cloning` step by descreasing the default value of the minimum number of cells per clone, since you have only a few cells (see more info [here](https://github.com/raphael-group/chisel/blob/master/guides/clones.md).

Please feel free to re-open the issue if the problem persists.
