### ISSUE TITLE
ZeroDivisionError  in the nonnormal mode

### ISSUE THREAD

**Issue by kzb193** [raphael-group/chisel#35]
Hello,

I am trying to apply chisel_nonormal on a 10x scDNAseq data. But, I am getting a long sequence of error messages that appears to be similar. Can you please help me with this? 

Specifically, I have applied the following steps.

1) used full automatic installation, and completed the quick start check.
2) called snps from the tumor bam  as 
 bcftools mpileup --ignore-RG --threads 10 -f $REF $BAM | bcftools call -mv -Oz -o $F_OUT
3) used eagle2 for phasing based on 1000 Genomes Phase 3 panel, and 
there are 1344782 many phased het. snps distributed across  chr 1-22 in the resulting vcf file.
4) called chisel as
chisel_nonormal -t ${TUM} -r ${REF} -l ${PHA}  --seed 12

An empty bcf.tsv file is generated along with a log file which is attached here as baf_log.txt
[baf_log.txt](https://github.com/raphael-group/chisel/files/14874124/baf_log.txt)
Additionally, the log file generated in the 'rdr' folder is attached here as rdr_log.txt
[rdr_log.txt](https://github.com/raphael-group/chisel/files/14874159/rdr_log.txt)

**A portion from the flow of error messages**

Traceback (most recent call last):
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/site-packages/chisel/Combiner.py", line 234, in init
    alpha_correct = args['significance'] / (20 * float(sum(len(snps[c]) for c in snps)))
ZeroDivisionError: float division by zero
Process PoolWorker-4233311:
Traceback (most recent call last):
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/net/mulan/home/kalinsba/apps/chisel/conda/envs/chisel/lib/python2.7/site-packages/chisel/Combiner.py", line 234, in init
    alpha_correct = args['significance'] / (20 * float(sum(len(snps[c]) for c in snps)))
....................................................................

Please let me know if you need any other details. Thank you!

**Comment by kzb193** [comment]
Hello,

Can you please help me out on this issue?

Thanks.
